platform :ios, '15.0'

target 'ImagineMyApps' do
  use_frameworks! :linkage => :static

  # React Native
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled] || true,
    :fabric_enabled => flags[:fabric_enabled] || false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Expo modules
  use_expo_modules!

  # Post install
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
